# Generated by Django 4.2 on 2023-05-06 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_message_ad"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Time of creation"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update time"),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.RemoveField(model_name="message", name="target",),
        migrations.AddField(
            model_name="message",
            name="chat",
            field=models.ForeignKey(
                help_text="Who receive message.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="api.chat",
            ),
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Time of creation"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update time"),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        help_text="Chat.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.chat",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Participant of the chat.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("chat", "user")},},
        ),
    ]
