# Generated by Django 4.2 on 2023-05-07 13:05

import api.models.attachment
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_chat_remove_message_target_message_chat_participant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Time of creation"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update time"),
                ),
                (
                    "file",
                    models.FileField(upload_to=api.models.attachment.custom_upload_to),
                ),
                ("title", models.CharField(help_text="Title of ad.", max_length=128)),
            ],
            options={"ordering": ["title"],},
        ),
        migrations.RemoveField(model_name="ad", name="description",),
        migrations.AddField(
            model_name="user",
            name="surname",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="participant",
            name="chat",
            field=models.ForeignKey(
                help_text="Chat.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="api.chat",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="user",
            field=models.ForeignKey(
                help_text="Participant of the chat.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
