# Generated by Django 4.2 on 2023-05-22 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_daysubject_group_professor_subject_weektimetable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(help_text='Group.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.group')),
                ('professor', models.ForeignKey(blank=True, help_text='Teacher of the group.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.professor')),
                ('subject', models.ForeignKey(help_text='Discipline.', on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
            ],
        ),
        migrations.DeleteModel(
            name='GroupTeacher',
        ),
        migrations.AlterField(
            model_name='group',
            name='teachers',
            field=models.ManyToManyField(through='api.GroupProfessor', to='api.professor'),
        ),
    ]
