# Generated by Django 4.2 on 2023-05-28 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_teachers_group_professors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='participant',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='user',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
